draw_bold_text_with_bright_colors = false
custom_cursor_colors = true
live_config_reload = true

[window]
dynamic_padding = false
decorations = "Full"
startup_mode = "Fullscreen"
opacity = 1

  [window.dimensions]
  columns = 100
  lines = 85

  [window.padding]
  x = 0
  y = 0

[scrolling]
history = 0
multiplier = 3

[font]
size = 14
use_thin_strokes = true

  [font.normal]
  family = "DaddyTime"
  style = "Light"

  [font.bold]
  family = "Iosevka"
  style = "Medium"

  [font.italic]
  family = "Iosevka"
  style = "Light Italic"

  [font.offset]
  x = 0
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0

[colors.primary]
background = "0xffffff"
foreground = "0x4d4d4c"

[colors.cursor]
text = "0xffffff"
cursor = "0x4d4d4c"

[colors.normal]
black = "0xffffff"
red = "0xc82829"
green = "0x718c00"
yellow = "0xeab700"
blue = "0x4271ae"
magenta = "0x8959a8"
cyan = "0x3e999f"
white = "0x4d4d4c"

[colors.bright]
black = "0x8e908c"
red = "0xf5871f"
green = "0xe0e0e0"
yellow = "0xd6d6d6"
blue = "0x969896"
magenta = "0x282a2e"
cyan = "0xa3685a"
white = "0x1d1f21"

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[[key_bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[key_bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[key_bindings]]
key = "Q"
mods = "Command"
action = "Quit"

[[key_bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[key_bindings]]
key = "Return"
mods = "Command"
action = "ToggleFullscreen"

[[key_bindings]]
key = "Home"
chars = "\u001bOH"
mode = "AppCursor"

[[key_bindings]]
key = "Home"
chars = "\u001b[H"
mode = "~AppCursor"

[[key_bindings]]
key = "End"
chars = "\u001bOF"
mode = "AppCursor"

[[key_bindings]]
key = "End"
chars = "\u001b[F"
mode = "~AppCursor"

[[key_bindings]]
key = "Equals"
mods = "Command"
action = "IncreaseFontSize"

[[key_bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"

[[key_bindings]]
key = "Minus"
mods = "Command|Shift"
action = "ResetFontSize"

[[key_bindings]]
key = "PageUp"
mods = "Shift"
chars = "\u001b[5;2~"

[[key_bindings]]
key = "PageUp"
mods = "Control"
chars = "\u001b[5;5~"

[[key_bindings]]
key = "PageUp"
chars = "\u001b[5~"

[[key_bindings]]
key = "PageDown"
mods = "Shift"
chars = "\u001b[6;2~"

[[key_bindings]]
key = "PageDown"
mods = "Control"
chars = "\u001b[6;5~"

[[key_bindings]]
key = "PageDown"
chars = "\u001b[6~"

[[key_bindings]]
key = "Left"
mods = "Shift"
chars = "\u001b[1;2D"

[[key_bindings]]
key = "Left"
mods = "Control"
chars = "\u001b[1;5D"

[[key_bindings]]
key = "Left"
mods = "Alt"
chars = "\u001b[1;3D"

[[key_bindings]]
key = "Left"
chars = "\u001b[D"
mode = "~AppCursor"

[[key_bindings]]
key = "Left"
chars = "\u001bOD"
mode = "AppCursor"

[[key_bindings]]
key = "Right"
mods = "Shift"
chars = "\u001b[1;2C"

[[key_bindings]]
key = "Right"
mods = "Control"
chars = "\u001b[1;5C"

[[key_bindings]]
key = "Right"
mods = "Alt"
chars = "\u001b[1;3C"

[[key_bindings]]
key = "Right"
chars = "\u001b[C"
mode = "~AppCursor"

[[key_bindings]]
key = "Right"
chars = "\u001bOC"
mode = "AppCursor"

[[key_bindings]]
key = "Up"
mods = "Shift"
chars = "\u001b[1;2A"

[[key_bindings]]
key = "Up"
mods = "Control"
chars = "\u001b[1;5A"

[[key_bindings]]
key = "Up"
mods = "Alt"
chars = "\u001b[1;3A"

[[key_bindings]]
key = "Up"
chars = "\u001b[A"
mode = "~AppCursor"

[[key_bindings]]
key = "Up"
chars = "\u001bOA"
mode = "AppCursor"

[[key_bindings]]
key = "Down"
mods = "Shift"
chars = "\u001b[1;2B"

[[key_bindings]]
key = "Down"
mods = "Control"
chars = "\u001b[1;5B"

[[key_bindings]]
key = "Down"
mods = "Alt"
chars = "\u001b[1;3B"

[[key_bindings]]
key = "Down"
chars = "\u001b[B"
mode = "~AppCursor"

[[key_bindings]]
key = "Down"
chars = "\u001bOB"
mode = "AppCursor"

[[key_bindings]]
key = "Tab"
mods = "Shift"
chars = "\u001b[Z"

[[key_bindings]]
key = "F1"
chars = "\u001bOP"

[[key_bindings]]
key = "F2"
chars = "\u001bOQ"

[[key_bindings]]
key = "F3"
chars = "\u001bOR"

[[key_bindings]]
key = "F4"
chars = "\u001bOS"

[[key_bindings]]
key = "F5"
chars = "\u001b[15~"

[[key_bindings]]
key = "F6"
chars = "\u001b[17~"

[[key_bindings]]
key = "F7"
chars = "\u001b[18~"

[[key_bindings]]
key = "F8"
chars = "\u001b[19~"

[[key_bindings]]
key = "F9"
chars = "\u001b[20~"

[[key_bindings]]
key = "F10"
chars = "\u001b[21~"

[[key_bindings]]
key = "F11"
chars = "\u001b[23~"

[[key_bindings]]
key = "F12"
chars = "\u001b[24~"

[[key_bindings]]
key = "Back"
chars = "\u007f"

[[key_bindings]]
key = "Back"
mods = "Alt"
chars = "\u001b"

[[key_bindings]]
key = "Insert"
chars = "\u001b[2~"

[[key_bindings]]
key = "Delete"
chars = "\u001b[3~"

[[key_bindings]]
key = "W"
mods = "Command"
chars = "\u0002&"

[[key_bindings]]
key = "T"
mods = "Command"
chars = "\u0002c"

[[key_bindings]]
key = "RBracket"
mods = "Command|Shift"
chars = "\u0002n"

[[key_bindings]]
key = "LBracket"
mods = "Command|Shift"
chars = "\u0002p"

[[key_bindings]]
key = "RBracket"
mods = "Command"
chars = "\u0002o"

[[key_bindings]]
key = "LBracket"
mods = "Command"
chars = "\u0002;"

[[key_bindings]]
key = "F"
mods = "Command"
chars = "\u0002/"

[mouse]
hide_when_typing = true

  [mouse.double_click]
  threshold = 300

  [mouse.triple_click]
  threshold = 300

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = false

[[mouse_bindings]]
mouse = "Middle"
action = "PasteSelection"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
render_timer = false
persistent_logging = false
log_level = "OFF"
print_events = false
ref_test = false
