add_newline = false

[line_break]
disabled=false

[git_metrics]
# added_style = 'bold blue'
# format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
